version: '3'

services:

  mongodb:
    image: mongo:latest
#    environment:
#      MONGO_INITDB_DATABASE: database
#      MONGO_INITDB_ROOT_USERNAME: username
#      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
#
#  postgres:
#    image: postgres:latest
#    environment:
#      - POSTGRES_USER=postgres
#      - PGUSER=postgres
#      - POSTGRES_NAME=postgres
#      - POSTGRES_PASSWORD=postgres
#    ports:
#      - "5432:5432"
